-- main/go_id_registry.lua
-- ═══════════════════════════════════════════════════════
-- 🗺️  REGISTRO REVERSO DE IDS DE GO (GENERADO — no editar a mano)
-- ═══════════════════════════════════════════════════════
--
-- Regenerar con: python3 tools/generate_go_id_registry.py
-- (ejecutar tras añadir/renombrar instancias en las colecciones)
--
-- Resuelve go.get_id() → ruta del GO sin depender del reverse-hash del
-- engine (solo disponible en DEBUG). Ver cabecera del generador y
-- docs/DEV_GOTCHAS.md (gotcha release-variant).
--
-- Licencia: GPL-3.0-only
-- ═══════════════════════════════════════════════════════

local M = {}

local PATHS = {
	"/audio_manager",
	"/camera",
	"/climate_controller",
	"/collectibles",
	"/collectibles/btn_collectible",
	"/collectibles/collectible_object",
	"/cursor",
	"/enemies",
	"/enemies/enemy_cockroach",
	"/exhibition_objects",
	"/exhibition_objects/ME_100002",
	"/exhibition_objects/ME_100003",
	"/exhibition_objects/ME_100004",
	"/exhibition_objects/ME_100005",
	"/exhibition_objects/ME_132",
	"/exhibition_objects/ME_13561",
	"/exhibition_objects/ME_13564",
	"/exhibition_objects/ME_13570",
	"/exhibition_objects/ME_13588",
	"/exhibition_objects/ME_13590",
	"/exhibition_objects/ME_16061",
	"/exhibition_objects/ME_16121",
	"/exhibition_objects/ME_17109",
	"/exhibition_objects/ME_17110",
	"/exhibition_objects/ME_17727",
	"/exhibition_objects/ME_17757",
	"/exhibition_objects/ME_18125",
	"/exhibition_objects/ME_18169",
	"/exhibition_objects/ME_18558",
	"/exhibition_objects/ME_18649",
	"/exhibition_objects/ME_18704",
	"/exhibition_objects/ME_18888",
	"/exhibition_objects/ME_19002",
	"/exhibition_objects/ME_19014",
	"/exhibition_objects/ME_1905",
	"/exhibition_objects/ME_1911",
	"/exhibition_objects/ME_19635",
	"/exhibition_objects/ME_20",
	"/exhibition_objects/ME_20045",
	"/exhibition_objects/ME_20175",
	"/exhibition_objects/ME_20507",
	"/exhibition_objects/ME_22253",
	"/exhibition_objects/ME_23871",
	"/exhibition_objects/ME_23981",
	"/exhibition_objects/ME_23982",
	"/exhibition_objects/ME_23983",
	"/exhibition_objects/ME_24008",
	"/exhibition_objects/ME_24226",
	"/exhibition_objects/ME_2899",
	"/exhibition_objects/ME_3098",
	"/exhibition_objects/ME_3541",
	"/exhibition_objects/ME_3662",
	"/exhibition_objects/ME_4225",
	"/exhibition_objects/ME_4302",
	"/exhibition_objects/ME_43452",
	"/exhibition_objects/ME_43666",
	"/exhibition_objects/ME_43737",
	"/exhibition_objects/ME_45681",
	"/exhibition_objects/ME_4946",
	"/exhibition_objects/ME_4947",
	"/exhibition_objects/ME_4948",
	"/exhibition_objects/ME_5090",
	"/exhibition_objects/ME_5099",
	"/exhibition_objects/ME_5117",
	"/exhibition_objects/ME_5140",
	"/exhibition_objects/ME_5225",
	"/exhibition_objects/ME_5267",
	"/exhibition_objects/ME_5271",
	"/exhibition_objects/ME_6209",
	"/exhibition_objects/ME_6350",
	"/exhibition_objects/ME_6560",
	"/exhibition_objects/ME_7622",
	"/exhibition_objects/ME_7634",
	"/furniture",
	"/furniture/bookcase_bro",
	"/furniture/bookcase_ibe",
	"/furniture/bookcase_neo",
	"/furniture/bookcase_pal",
	"/furniture/bookcase_restor",
	"/furniture/bookcase_rom",
	"/furniture/door_front",
	"/furniture/door_front1",
	"/furniture/door_front2",
	"/furniture/door_front3",
	"/furniture/door_front4",
	"/furniture/door_front5",
	"/furniture/door_main",
	"/furniture/door_main1",
	"/furniture/door_main2",
	"/furniture/door_service",
	"/furniture/door_service1",
	"/furniture/door_side",
	"/furniture/door_side1",
	"/furniture/door_side10",
	"/furniture/door_side11",
	"/furniture/door_side12",
	"/furniture/door_side13",
	"/furniture/door_side14",
	"/furniture/door_side15",
	"/furniture/door_side16",
	"/furniture/door_side17",
	"/furniture/door_side18",
	"/furniture/door_side19",
	"/furniture/door_side2",
	"/furniture/door_side20",
	"/furniture/door_side21",
	"/furniture/door_side22",
	"/furniture/door_side23",
	"/furniture/door_side24",
	"/furniture/door_side25",
	"/furniture/door_side3",
	"/furniture/door_side4",
	"/furniture/door_side5",
	"/furniture/door_side6",
	"/furniture/door_side7",
	"/furniture/door_side8",
	"/furniture/door_side9",
	"/furniture/office_cabinet",
	"/furniture/office_cabinet1",
	"/furniture/office_cabinet2",
	"/furniture/office_cabinet3",
	"/furniture/office_cabinet4",
	"/furniture/office_cabinet5",
	"/furniture/slot_shelf_bro",
	"/furniture/slot_shelf_ibe",
	"/furniture/slot_shelf_neo",
	"/furniture/slot_shelf_pal",
	"/furniture/slot_shelf_rom",
	"/furniture/slot_showcase_bro",
	"/furniture/slot_showcase_bro1",
	"/furniture/slot_showcase_ibe",
	"/furniture/slot_showcase_ibe1",
	"/furniture/slot_showcase_neo",
	"/furniture/slot_showcase_neo1",
	"/furniture/slot_showcase_pal",
	"/furniture/slot_showcase_pal1",
	"/furniture/slot_showcase_rom",
	"/furniture/slot_showcase_rom2",
	"/game_manager",
	"/gui",
	"/gui_intro",
	"/gui_library",
	"/gui_victory",
	"/gui_web_controls",
	"/intro_animation",
	"/intro_animation/player_intro",
	"/intro_manager",
	"/inventory_manager",
	"/level2",
	"/level2/npcs",
	"/level2/npcs/cat",
	"/level2/npcs/npc_01",
	"/level2/npcs/npc_02",
	"/level2/npcs/npc_03",
	"/level2/npcs/npc_04",
	"/level2/npcs/npc_05",
	"/level2/npcs/npc_06",
	"/level2/npcs/npc_07",
	"/level2/npcs/npc_08",
	"/level2/npcs/npc_09",
	"/level2/npcs/npc_10",
	"/level2/npcs/npc_11",
	"/level2/npcs/npc_12",
	"/level2/npcs/npc_13",
	"/level2/npcs/npc_14",
	"/level2/npcs/spawn_npcs",
	"/level2/npcs/spawn_npcs/spawn_npc_01",
	"/level2/npcs/spawn_npcs/spawn_npc_02",
	"/level2/npcs/spawn_npcs/spawn_npc_03",
	"/level2/npcs/spawn_npcs/spawn_npc_04",
	"/level2/npcs/spawn_npcs/spawn_npc_05",
	"/level2/npcs/spawn_npcs/spawn_npc_06",
	"/level2/npcs/spawn_npcs/spawn_npc_07",
	"/level2/npcs/spawn_npcs/spawn_npc_08",
	"/level2/npcs/spawn_npcs/spawn_npc_09",
	"/level2/npcs/spawn_npcs/spawn_npc_10",
	"/level2/npcs/spawn_npcs/spawn_npc_11",
	"/level2/npcs/spawn_npcs/spawn_npc_12",
	"/level2/npcs/spawn_npcs/spawn_npc_13",
	"/level2/npcs/spawn_npcs/spawn_npc_14",
	"/level2/npcs/spawn_npcs/spawn_npc_cat",
	"/main_loader",
	"/nest_container",
	"/nest_container/nest_spawn_01",
	"/nest_container/nest_spawn_02",
	"/nest_container/nest_spawn_03",
	"/nest_container/nest_spawn_04",
	"/nest_container/nest_spawn_05",
	"/nest_container/nest_spawn_06",
	"/nest_container/nest_spawn_07",
	"/nest_container/nest_spawn_08",
	"/nest_container/nest_spawn_09",
	"/nest_container/nest_spawn_10",
	"/player",
	"/player/player_spray",
	"/player_spawn_point",
	"/props",
	"/props/bullet",
	"/props/car_end_point",
	"/props/car_start_point",
	"/props/food_spawn_container",
	"/props/food_spawn_container/food_spawn_01",
	"/props/food_spawn_container/food_spawn_02",
	"/props/food_spawn_container/food_spawn_03",
	"/props/kit_health",
	"/props/kit_stamina",
	"/props/spray_spawn_container",
	"/props/spray_spawn_container/spray_spawn_01",
	"/props/spray_spawn_container/spray_spawn_02",
	"/props/spray_spawn_container/spray_spawn_03",
	"/props/spray_spawn_container/spray_spawn_04",
	"/props/spray_spawn_container/spray_spawn_05",
	"/props/spray_spawn_container/spray_spawn_06",
	"/proxy_intro",
	"/proxy_level_01",
	"/spawn_collectibles",
	"/spawn_enemies",
	"/zones_sound",
	"/zones_sound/zone_intake",
	"/zones_sound/zone_storage",
}

local REG = nil

local function ensure_registry()
	if REG then return end
	REG = {}
	for i = 1, #PATHS do
		REG[hash(PATHS[i])] = PATHS[i]
	end
end

-- Ruta completa del GO ('/npcs/npc_01') o nil si no está registrada
-- (instancias creadas en runtime vía factory no están — sus scripts no
-- parsean ids).
function M.path_of(go_id)
	if go_id == nil then return nil end
	ensure_registry()
	return REG[go_id]
end

-- Último segmento de la ruta ('npc_01'). Fallback: parseo del tostring()
-- del hash — solo produce el nombre real en builds DEBUG (en release
-- devuelve basura; el registro de arriba es la fuente válida).
function M.name_of(go_id, default)
	local p = M.path_of(go_id)
	local s = p or tostring(go_id)
	local clean = s:match("%s*%[%s*(.-)%s*%]") or s
	local name = clean:match("([^/]+)$")
	if name then return name end
	return default
end

return M
